function Omlets_mobile(){var V='',S=' top: -1000px;',qb='" for "gwt:onLoadErrorFn"',ob='" for "gwt:onPropertyErrorFn"',_='");',rb='#',Db='&',Lb='.cache.js',tb='/',zb='//',Kb=':',ib='::',U='<!doctype html>',W='<html><head><\/head><body><\/body><\/html>',lb='=',sb='?',nb='Bad handler "',T='CSS1Compat',Z='Chrome',Y='DOMContentLoaded',N='DUMMY',Jb="GWT module 'Omlets_mobile' may need to be (re)compiled",L='Omlets_mobile',Ib='Omlets_mobile.devmode.js',xb='Omlets_mobile.nocache.js',hb='Omlets_mobile::',Gb='Unexpected exception in locale detection, using default: ',Fb='_',Eb='__gwt_Locale',yb='base',wb='baseUrl',I='begin',O='body',H='bootstrap',vb='clear.cache.gif',kb='content',Bb='en',Nb='end',$='eval("',J='gwt.codesvr.Omlets_mobile=',K='gwt.codesvr=',pb='gwt:onLoadErrorFn',mb='gwt:onPropertyErrorFn',jb='gwt:property',eb='head',P='iframe',ub='img',bb='javascript',Q='javascript:""',Mb='loadExternalRefs',Ab='locale',Cb='locale=',fb='meta',db='moduleRequested',cb='moduleStartup',gb='name',R='position:absolute; width:0; height:0; border:none; left: -1000px;',ab='script',Hb='selectingPermutation',M='startup',X='undefined';var p=window;var q=document;s(H,I);function r(){var a=p.location.search;return a.indexOf(J)!=-1||a.indexOf(K)!=-1}
function s(a,b){if(p.__gwtStatsEvent){p.__gwtStatsEvent({moduleName:L,sessionId:p.__gwtStatsSessionId,subSystem:M,evtGroup:a,millis:(new Date).getTime(),type:b})}}
Omlets_mobile.__sendStats=s;Omlets_mobile.__moduleName=L;Omlets_mobile.__errFn=null;Omlets_mobile.__moduleBase=N;Omlets_mobile.__softPermutationId=0;Omlets_mobile.__computePropValue=null;Omlets_mobile.__getPropMap=null;Omlets_mobile.__gwtInstallCode=function(){};Omlets_mobile.__gwtStartLoadingFragment=function(){return null};var t=function(){return false};var u=function(){return null};__propertyErrorFunction=null;var v=p.__gwt_activeModules=p.__gwt_activeModules||{};v[L]={moduleName:L};var w;function x(){z();return w}
function y(){z();return w.getElementsByTagName(O)[0]}
function z(){if(w){return}var a=q.createElement(P);a.src=Q;a.id=L;a.style.cssText=R+S;a.tabIndex=-1;q.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==T?U:V;w.write(b+W);w.close()}
function A(k){function l(a){function b(){if(typeof q.readyState==X){return typeof q.body!=X&&q.body!=null}return /loaded|complete/.test(q.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(q.removeEventListener){q.removeEventListener(Y,d,false)}if(e){clearInterval(e)}}}
if(q.addEventListener){q.addEventListener(Y,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=y();var f=x();var g;if(navigator.userAgent.indexOf(Z)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode($));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(_));g=f.createElement(ab);g.language=bb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(ab);g.language=bb;g.text=c[i];e.appendChild(g);d(e,g)}}}
Omlets_mobile.onScriptDownloaded=function(a){l(function(){m(a)})};s(cb,db);var n=q.createElement(ab);n.src=k;q.getElementsByTagName(eb)[0].appendChild(n)}
Omlets_mobile.__startLoadingFragment=function(a){return D(a)};Omlets_mobile.__installRunAsyncCode=function(a){var b=y();var c=x().createElement(ab);c.language=bb;c.text=a;b.appendChild(c);b.removeChild(c)};function B(){var c={};var d;var e;var f=q.getElementsByTagName(fb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(gb),k;if(j){j=j.replace(hb,V);if(j.indexOf(ib)>=0){continue}if(j==jb){k=i.getAttribute(kb);if(k){var l,m=k.indexOf(lb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=V}c[j]=l}}else if(j==mb){k=i.getAttribute(kb);if(k){try{d=eval(k)}catch(a){alert(nb+k+ob)}}}else if(j==pb){k=i.getAttribute(kb);if(k){try{e=eval(k)}catch(a){alert(nb+k+qb)}}}}}u=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;Omlets_mobile.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(rb);if(b==-1){b=a.length}var c=a.indexOf(sb);if(c==-1){c=a.length}var d=a.lastIndexOf(tb,Math.min(c,b));return d>=0?a.substring(0,d+1):V}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=q.createElement(ub);b.src=a+vb;a=e(b.src)}return a}
function g(){var a=u(wb);if(a!=null){return a}return V}
function h(){var a=q.getElementsByTagName(ab);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(xb)!=-1){return e(a[b].src)}}return V}
function i(){var a=q.getElementsByTagName(yb);if(a.length>0){return a[a.length-1].href}return V}
function j(){var a=q.location;return a.href==a.protocol+zb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==V){k=h()}if(k==V){k=i()}if(k==V&&j()){k=e(q.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return Omlets_mobile.__moduleBase+a}
function E(){var i=[];var j;var k=[];var l=[];function m(a){var b=l[a](),c=k[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
l[Ab]=function(){var b=null;var c=Bb;try{if(!b){var d=location.search;var e=d.indexOf(Cb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Db,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=u(Ab)}if(!b){b=p[Eb]}if(b){c=b}while(b&&!t(Ab,b)){var h=b.lastIndexOf(Fb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Gb+a)}p[Eb]=c;return b||Bb};k[Ab]={cs:0,de:1,'default':2,el:3,en:4,es:5,fr:6,it:7,ja:8,nl:9,pt:10,ru:11,zh:12};t=function(a,b){return b in k[a]};Omlets_mobile.__getPropMap=function(){var a={};for(var b in k){if(k.hasOwnProperty(b)){a[b]=m(b)}}return a};Omlets_mobile.__computePropValue=m;p.__gwt_activeModules[L].bindings=Omlets_mobile.__getPropMap;s(H,Hb);if(r()){return D(Ib)}var n;try{alert(Jb);return;var o=n.indexOf(Kb);if(o!=-1){j=parseInt(n.substring(o+1),10);n=n.substring(0,o)}}catch(a){}Omlets_mobile.__softPermutationId=j;return D(n+Lb)}
function F(){if(!p.__gwt_stylesLoaded){p.__gwt_stylesLoaded={}}s(Mb,I);s(Mb,Nb)}
B();Omlets_mobile.__moduleBase=C();v[L].moduleBase=Omlets_mobile.__moduleBase;var G=E();F();s(H,Nb);A(G);return true}
Omlets_mobile.succeeded=Omlets_mobile();